import { isMobilePerformanceMode } from "../input/performanceMode";

export const MOBILE_PERFORMANCE_MODE = isMobilePerformanceMode();

export const FIREBALL_SPEED = 80;
export const ICESPELL_SPEED = 60;
export const ICESHARD_SPEED = 70;
export const RINGSOFPOWER_SPEED = 40;
export const LIGHTNING_SPEED = 120;

export const GRAB_MAX_REACH = 40;
export const GRAB_TARGET_RADIUS = 1.8;

export const TORNADO_RADIUS = 17;
export const TORNADO_DURATION = 8000;
export const TORNADO_BAND_COUNT = MOBILE_PERFORMANCE_MODE ? 4 : 5;
export const TORNADO_GROUND_DUST_COUNT = MOBILE_PERFORMANCE_MODE ? 4 : 7;
export const TORNADO_LOOSE_PIXEL_COUNT = MOBILE_PERFORMANCE_MODE ? 3 : 5;
export const TORNADO_ORBIT_PIXEL_COUNT = MOBILE_PERFORMANCE_MODE ? 3 : 6;

export const METEOR_SHOWER_RADIUS = 15;
export const METEOR_SHOWER_DURATION = 6500;
export const METEOR_SHOWER_METEOR_COUNT = MOBILE_PERFORMANCE_MODE ? 3 : 5;
export const METEOR_EXPLOSION_PARTICLE_COUNT = MOBILE_PERFORMANCE_MODE ? 1 : 3;
export const METEOR_AREA_SEGMENTS = MOBILE_PERFORMANCE_MODE ? 14 : 24;
export const METEOR_IMPACT_SEGMENTS = MOBILE_PERFORMANCE_MODE ? 8 : 12;

export const SPELL_FORCE_EVENT_INTERVAL = MOBILE_PERFORMANCE_MODE ? 1 / 20 : 1 / 30;
export const SPELL_VISUAL_UPDATE_INTERVAL = MOBILE_PERFORMANCE_MODE ? 1 / 24 : 0;

export const SMOKE_CLOUD_PARTICLE_COUNT = MOBILE_PERFORMANCE_MODE ? 6 : 8;
