import * as THREE from "three";

export type SurvivalBotwGrassCenter = {
  x: number;
  y: number;
  z: number;
};

export type SurvivalBotwGrassBladeInstance = {
  x: number;
  y: number;
  z: number;
  normalX: number;
  normalY: number;
  normalZ: number;
  yaw: number;
  width: number;
  height: number;
  colorR: number;
  colorG: number;
  colorB: number;
};

export type SurvivalBotwFlowerType = "round" | "star" | "bell" | "puff";

export type SurvivalBotwFlowerInstance = {
  x: number;
  y: number;
  z: number;
  normalX: number;
  normalY: number;
  normalZ: number;
  yaw: number;
  stemHeight: number;
  stemRadius: number;
  leafCount: number;
  leafWidth: number;
  leafLength: number;
  leafHeight: number;
  leafYawOffset: number;
  leafColorR: number;
  leafColorG: number;
  leafColorB: number;
  bloomSize: number;
  bloomWidth: number;
  bloomHeight: number;
  bloomType: SurvivalBotwFlowerType;
  largeBloomAmount?: number;
  colorR: number;
  colorG: number;
  colorB: number;
};

export const SURVIVAL_BOTW_GRASS_RADIUS = 224;
export const SURVIVAL_BOTW_GRASS_AIR_RADIUS = 304;
export const SURVIVAL_BOTW_GRASS_EDGE_FADE = 34;
export const SURVIVAL_BOTW_GRASS_CENTER_STEP = 96;
export const SURVIVAL_BOTW_GRASS_RECENTER_DISTANCE = 64;
export const SURVIVAL_BOTW_GRASS_PREWARM_VIEWER_DISTANCE = 22;
export const SURVIVAL_BOTW_GRASS_LEAD_SECONDS = 4.2;
export const SURVIVAL_BOTW_GRASS_MIN_LEAD_DISTANCE = 142;
export const SURVIVAL_BOTW_GRASS_FAST_MIN_LEAD_DISTANCE = 188;
export const SURVIVAL_BOTW_GRASS_FAST_LEAD_SPEED = 8;
export const SURVIVAL_BOTW_GRASS_LEAD_SMOOTHING = 8.5;
export const SURVIVAL_BOTW_GRASS_MIN_CENTER_TRAVEL_ALIGNMENT = -0.04;
export const SURVIVAL_BOTW_GRASS_MAX_LEAD_DISTANCE = 328;
export const SURVIVAL_BOTW_GRASS_PENDING_VIEWER_SAFE_DISTANCE = 46;
export const SURVIVAL_BOTW_GRASS_PENDING_TARGET_SAFE_DISTANCE = 64;
export const SURVIVAL_BOTW_GRASS_PREWARM_DISTANCE = 6;
export const SURVIVAL_BOTW_GRASS_PREWARM_AHEAD_STEPS = 4;
export const SURVIVAL_BOTW_GRASS_NEIGHBOR_PREWARM_INTERVAL_SECONDS = 0.35;
export const SURVIVAL_BOTW_GRASS_UPLOAD_NEAR_PRIORITY_RADIUS = 156;
export const SURVIVAL_BOTW_GRASS_UPLOAD_MID_PRIORITY_RADIUS = 218;
export const SURVIVAL_BOTW_GRASS_UPLOAD_RECENTER_MIN_PROGRESS = 0.78;
export const SURVIVAL_BOTW_GRASS_UPLOAD_RECENTER_EDGE_RELEASE_DISTANCE = SURVIVAL_BOTW_GRASS_RADIUS * 0.72;
export const SURVIVAL_BOTW_GRASS_RECENTER_MIN_INTERVAL_SECONDS = 0.65;
export const SURVIVAL_BOTW_GRASS_RECENTER_VIEWER_DRIFT_RELEASE = SURVIVAL_BOTW_GRASS_RADIUS * 0.5;
export const SURVIVAL_BOTW_GRASS_RECENTER_MAX_VIEWER_DISTANCE = SURVIVAL_BOTW_GRASS_RADIUS * 0.5;
export const SURVIVAL_BOTW_GRASS_RECENTER_MAX_VIEWER_DISTANCE_INCREASE = 24;
export const SURVIVAL_BOTW_GRASS_RECENTER_EMERGENCY_VIEWER_DISTANCE = SURVIVAL_BOTW_GRASS_RADIUS + SURVIVAL_BOTW_GRASS_EDGE_FADE * 1.5;
export const SURVIVAL_BOTW_GRASS_PREVIEW_RECENTER_VIEWER_DISTANCE = SURVIVAL_BOTW_GRASS_RADIUS * 0.82;
export const SURVIVAL_BOTW_GRASS_DESKTOP_COUNT = 56000;
export const SURVIVAL_BOTW_GRASS_MOBILE_COUNT = SURVIVAL_BOTW_GRASS_DESKTOP_COUNT;
export const SURVIVAL_BOTW_GRASS_CARPET_RADIUS = 252;
export const SURVIVAL_BOTW_GRASS_CARPET_AIR_RADIUS = 326;
export const SURVIVAL_BOTW_GRASS_CARPET_EDGE_FADE = 68;
export const SURVIVAL_BOTW_GRASS_CARPET_SEGMENTS = 52;
export const SURVIVAL_BOTW_GRASS_CARPET_ENABLED = false;
export const SURVIVAL_BOTW_GRASS_FOOTPRINT_SCALE = 0.66;
export const SURVIVAL_BOTW_GRASS_MAX_FOOTPRINT_HEIGHT_RANGE = 24;
export const SURVIVAL_BOTW_GRASS_BLADE_MIN_NORMAL_Y = 0.68;
export const SURVIVAL_BOTW_GRASS_FLOWER_MIN_NORMAL_Y = 0.84;
export const SURVIVAL_BOTW_GRASS_FLUSH_FOOTPRINT_RANGE = 4.2;
export const SURVIVAL_BOTW_GRASS_SLOPE_FOOTPRINT_RANGE = 1.35;
export const SURVIVAL_BOTW_FLOWER_FLUSH_FOOTPRINT_RANGE = 1.28;
export const SURVIVAL_BOTW_DECORATION_MIN_NORMAL_Y = 0.72;
export const SURVIVAL_BOTW_DECORATION_MAX_FOOTPRINT_RANGE = 7.4;
export const SURVIVAL_BOTW_HILLSIDE_GRASS_START_Y = 18;
export const SURVIVAL_BOTW_HILLSIDE_GRASS_FULL_Y = 58;
export const SURVIVAL_BOTW_GRASS_BLADE_NEAR_HEIGHT_LIMIT = 56;
export const SURVIVAL_BOTW_GRASS_BLADE_FAR_HEIGHT_LIMIT = 42;
export const SURVIVAL_BOTW_GRASS_VERTICAL_FADE_START = 54;
export const SURVIVAL_BOTW_GRASS_VERTICAL_FADE_END = 132;
export const SURVIVAL_BOTW_GRASS_FLAT_NORMAL_Y = 0.992;
export const SURVIVAL_BOTW_FLOWER_NEAR_HEIGHT_LIMIT = 34;
export const SURVIVAL_BOTW_FLOWER_FAR_HEIGHT_LIMIT = 24;
export const SURVIVAL_BOTW_GRASS_FLOWER_DESKTOP_COUNT = 760;
export const SURVIVAL_BOTW_GRASS_FLOWER_MOBILE_COUNT = SURVIVAL_BOTW_GRASS_FLOWER_DESKTOP_COUNT;
export const SURVIVAL_BOTW_GRASS_TALL_FLOWER_FEATURE_COUNT = 18;
export const SURVIVAL_BOTW_GRASS_FLOWER_DESKTOP_RADIUS_SCALE = 0.84;
export const SURVIVAL_BOTW_GRASS_FLOWER_MOBILE_RADIUS_SCALE = SURVIVAL_BOTW_GRASS_FLOWER_DESKTOP_RADIUS_SCALE;
export const SURVIVAL_BOTW_GRASS_FLOWER_VISIBLE_RADIUS = SURVIVAL_BOTW_GRASS_RADIUS * 0.78;
export const SURVIVAL_BOTW_GRASS_FLOWER_VISIBLE_FADE = 92;
export const SURVIVAL_BOTW_GRASS_CANDIDATE_MULTIPLIER = 1.16;
export const SURVIVAL_BOTW_GRASS_BUILD_DESKTOP_SLICE_CANDIDATES = 4200;
export const SURVIVAL_BOTW_GRASS_BUILD_MOBILE_SLICE_CANDIDATES = 4200;
export const SURVIVAL_BOTW_GRASS_BUILD_DESKTOP_SLICE_MS = 4.8;
export const SURVIVAL_BOTW_GRASS_BUILD_MOBILE_SLICE_MS = 4.8;
export const SURVIVAL_BOTW_GRASS_BUILD_SLICE_DELAY_MS = 0;
export const SURVIVAL_BOTW_GRASS_MAX_PENDING_PREWARMS = 5;
export const SURVIVAL_BOTW_GRASS_MAX_DIRECTIONAL_PENDING_PREWARMS = 4;
export const SURVIVAL_BOTW_GRASS_MAX_BACKGROUND_PENDING_PREWARMS = 2;
export const SURVIVAL_BOTW_GRASS_BOOTSTRAP_DESKTOP_COUNT = 22000;
export const SURVIVAL_BOTW_GRASS_BOOTSTRAP_MOBILE_COUNT = SURVIVAL_BOTW_GRASS_BOOTSTRAP_DESKTOP_COUNT;
export const SURVIVAL_BOTW_GRASS_BOOTSTRAP_DESKTOP_RADIUS_SCALE = 0.98;
export const SURVIVAL_BOTW_GRASS_BOOTSTRAP_MOBILE_RADIUS_SCALE = SURVIVAL_BOTW_GRASS_BOOTSTRAP_DESKTOP_RADIUS_SCALE;
export const SURVIVAL_BOTW_GRASS_BOOTSTRAP_CANDIDATE_MULTIPLIER = 1.1;
export const SURVIVAL_BOTW_GRASS_DESKTOP_PREVIEW_COUNT = 9000;
export const SURVIVAL_BOTW_GRASS_MOBILE_PREVIEW_COUNT = SURVIVAL_BOTW_GRASS_DESKTOP_PREVIEW_COUNT;
export const SURVIVAL_BOTW_GRASS_DESKTOP_PREVIEW_MIN_COUNT = 6500;
export const SURVIVAL_BOTW_GRASS_MOBILE_PREVIEW_MIN_COUNT = SURVIVAL_BOTW_GRASS_DESKTOP_PREVIEW_MIN_COUNT;
export const SURVIVAL_BOTW_GRASS_PREVIEW_MAX_WAIT_MS = 620;
export const SURVIVAL_BOTW_GRASS_PREVIEW_REFRESH_COUNT = 6000;
export const SURVIVAL_BOTW_GRASS_PREVIEW_REFRESH_MS = 720;
export const SURVIVAL_BOTW_GRASS_UPLOAD_DESKTOP_BATCH = 1800;
export const SURVIVAL_BOTW_GRASS_UPLOAD_MOBILE_BATCH = 2400;
export const SURVIVAL_BOTW_GRASS_UPLOAD_DESKTOP_INITIAL_BATCH = 9800;
export const SURVIVAL_BOTW_GRASS_UPLOAD_MOBILE_INITIAL_BATCH = 9000;
export const SURVIVAL_BOTW_GRASS_BUILD_CACHE_LIMIT = 36;
export const SURVIVAL_BOTW_GRASS_NEIGHBOR_PREWARM_OFFSETS: ReadonlyArray<readonly [number, number]> = [
  [1, 0],
  [0, 1],
  [-1, 0],
  [0, -1],
  [1, 1],
  [1, -1],
  [-1, 1],
  [-1, -1],
  [2, 0],
  [0, 2],
  [-2, 0],
  [0, -2],
];
export const SURVIVAL_BOTW_HILLSIDE_GRASS_MUTE_COLOR = new THREE.Color("#667f43");
export const SURVIVAL_BOTW_HILLSIDE_GRASS_DRY_COLOR = new THREE.Color("#89925a");
