import * as THREE from "three";

export const SURVIVAL_WORLD_GRASS_BLADES_PER_TUFT = 4;
export const SURVIVAL_GRASS_BLADE_SOURCE_UP = new THREE.Vector3(0, 1, 0);
export const SURVIVAL_GROUND_GRASS_SOURCE_NORMAL = new THREE.Vector3(0, 0, 1);
export const MOBILE_SURVIVAL_GRASS_WIND_UPDATE_INTERVAL_SECONDS = 1 / 24;
export const MOBILE_SURVIVAL_GRASS_FIELD_UPDATE_INTERVAL_SECONDS = 1 / 30;
