import {
  SURVIVAL_BOTW_GRASS_CENTER_STEP,
  SURVIVAL_BOTW_GRASS_EDGE_FADE,
  SURVIVAL_BOTW_GRASS_PENDING_TARGET_SAFE_DISTANCE,
  SURVIVAL_BOTW_GRASS_PENDING_VIEWER_SAFE_DISTANCE,
  SURVIVAL_BOTW_GRASS_PREVIEW_RECENTER_VIEWER_DISTANCE,
  SURVIVAL_BOTW_GRASS_PREWARM_DISTANCE,
  SURVIVAL_BOTW_GRASS_PREWARM_VIEWER_DISTANCE,
  SURVIVAL_BOTW_GRASS_RADIUS,
  SURVIVAL_BOTW_GRASS_RECENTER_DISTANCE,
  SURVIVAL_BOTW_GRASS_RECENTER_EMERGENCY_VIEWER_DISTANCE,
  SURVIVAL_BOTW_GRASS_RECENTER_MAX_VIEWER_DISTANCE,
  SURVIVAL_BOTW_GRASS_RECENTER_VIEWER_DRIFT_RELEASE,
  SURVIVAL_BOTW_GRASS_UPLOAD_RECENTER_EDGE_RELEASE_DISTANCE,
  type SurvivalBotwGrassCenter,
} from "./survivalBotwGrassConfig";

const SURVIVAL_BOTW_GRASS_SLICE_CLOCK_CHECK_INTERVAL = 16;

export const MOBILE_BOTW_GRASS_WIND_UPDATE_INTERVAL_SECONDS = 1 / 24;
export const SURVIVAL_BOTW_GRASS_PENDING_VIEWER_SAFE_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_PENDING_VIEWER_SAFE_DISTANCE * SURVIVAL_BOTW_GRASS_PENDING_VIEWER_SAFE_DISTANCE;
export const SURVIVAL_BOTW_GRASS_PENDING_TARGET_SAFE_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_PENDING_TARGET_SAFE_DISTANCE * SURVIVAL_BOTW_GRASS_PENDING_TARGET_SAFE_DISTANCE;
export const SURVIVAL_BOTW_GRASS_UPLOAD_RECENTER_EDGE_RELEASE_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_UPLOAD_RECENTER_EDGE_RELEASE_DISTANCE * SURVIVAL_BOTW_GRASS_UPLOAD_RECENTER_EDGE_RELEASE_DISTANCE;
export const SURVIVAL_BOTW_GRASS_RECENTER_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_RECENTER_DISTANCE * SURVIVAL_BOTW_GRASS_RECENTER_DISTANCE;
export const SURVIVAL_BOTW_GRASS_TARGET_RECENTER_DISTANCE =
  SURVIVAL_BOTW_GRASS_RADIUS - SURVIVAL_BOTW_GRASS_EDGE_FADE * 0.35;
export const SURVIVAL_BOTW_GRASS_TARGET_RECENTER_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_TARGET_RECENTER_DISTANCE * SURVIVAL_BOTW_GRASS_TARGET_RECENTER_DISTANCE;
export const SURVIVAL_BOTW_GRASS_PREWARM_VIEWER_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_PREWARM_VIEWER_DISTANCE * SURVIVAL_BOTW_GRASS_PREWARM_VIEWER_DISTANCE;
export const SURVIVAL_BOTW_GRASS_PREWARM_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_PREWARM_DISTANCE * SURVIVAL_BOTW_GRASS_PREWARM_DISTANCE;
export const SURVIVAL_BOTW_GRASS_PREVIEW_RECENTER_VIEWER_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_PREVIEW_RECENTER_VIEWER_DISTANCE * SURVIVAL_BOTW_GRASS_PREVIEW_RECENTER_VIEWER_DISTANCE;
export const SURVIVAL_BOTW_GRASS_RECENTER_EMERGENCY_VIEWER_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_RECENTER_EMERGENCY_VIEWER_DISTANCE * SURVIVAL_BOTW_GRASS_RECENTER_EMERGENCY_VIEWER_DISTANCE;
export const SURVIVAL_BOTW_GRASS_RECENTER_VIEWER_DRIFT_RELEASE_SQ =
  SURVIVAL_BOTW_GRASS_RECENTER_VIEWER_DRIFT_RELEASE * SURVIVAL_BOTW_GRASS_RECENTER_VIEWER_DRIFT_RELEASE;
export const SURVIVAL_BOTW_GRASS_RECENTER_MAX_VIEWER_DISTANCE_SQ =
  SURVIVAL_BOTW_GRASS_RECENTER_MAX_VIEWER_DISTANCE * SURVIVAL_BOTW_GRASS_RECENTER_MAX_VIEWER_DISTANCE;
export const SURVIVAL_BOTW_GRASS_DEBUG_SAMPLE_OFFSETS = [-40, -10, 15, 40, 70, 100, 135, 175, 220, 270] as const;

export type SurvivalBotwGrassNeighborPrewarmState = {
  centerKey: string;
  offsetIndex: number;
  lastAt: number;
  travelOffsets: Array<[number, number]>;
  seenOffsets: Array<[number, number]>;
};

export type SurvivalBotwGrassDebugSampleResolver = (worldX: number, worldZ: number) => Record<string, unknown>;

export function getSurvivalBotwGrassNowMs() {
  return typeof performance !== "undefined" ? performance.now() : Date.now();
}

export function shouldContinueSurvivalBotwGrassSlice(
  workCount: number,
  sliceStartedAt: number,
  sliceBudgetMs: number,
) {
  if (workCount === 0 || workCount % SURVIVAL_BOTW_GRASS_SLICE_CLOCK_CHECK_INTERVAL !== 0) return true;
  return getSurvivalBotwGrassNowMs() - sliceStartedAt < sliceBudgetMs;
}

export function getSurvivalBotwGrassElapsedMs(startedAt: number) {
  return getSurvivalBotwGrassNowMs() - startedAt;
}

export function makeSurvivalBotwGrassOffsetScratch(count: number): Array<[number, number]> {
  const offsets: Array<[number, number]> = [];
  for (let index = 0; index < count; index += 1) {
    offsets.push([0, 0]);
  }
  return offsets;
}

export function getSurvivalBotwGrassSnappedCenter(
  worldX: number,
  worldY: number,
  worldZ: number,
): SurvivalBotwGrassCenter {
  return {
    x: Math.round(worldX / SURVIVAL_BOTW_GRASS_CENTER_STEP) * SURVIVAL_BOTW_GRASS_CENTER_STEP,
    y: worldY,
    z: Math.round(worldZ / SURVIVAL_BOTW_GRASS_CENTER_STEP) * SURVIVAL_BOTW_GRASS_CENTER_STEP,
  };
}

export function getSurvivalBotwGrassDebugLineSamples(
  viewerX: number,
  viewerZ: number,
  sampleAt: SurvivalBotwGrassDebugSampleResolver,
) {
  const debugSamples = [];
  for (let index = 0; index < SURVIVAL_BOTW_GRASS_DEBUG_SAMPLE_OFFSETS.length; index += 1) {
    const offset = SURVIVAL_BOTW_GRASS_DEBUG_SAMPLE_OFFSETS[index];
    debugSamples.push({
      offset,
      ...sampleAt(viewerX + offset, viewerZ),
    });
  }
  return debugSamples;
}
